function [cineq, ceq, cineqGrad, ceqGrad] = generatedConstraints(inputVariables, extraParams)
%generatedConstraints Compute constraint values and gradients
%
%   [CINEQ, CEQ] = generatedConstraints(INPUTVARIABLES, EXTRAPARAMS)
%   computes the inequality constraint values CINEQ and the equality
%   constraint values CEQ at the point INPUTVARIABLES, using the extra
%   parameters in EXTRAPARAMS.
%
%   [CINEQ, CEQ, CINEQGRAD, CEQGRAD] =
%   generatedConstraints(INPUTVARIABLES, EXTRAPARAMS) additionally
%   computes the inequality constraint gradient values CINEQGRAD and the
%   equality constraint gradient values CEQGRAD at the current point.
%
%   Auto-generated by prob2struct on 06-Oct-2022 14:42:18

%% Compute inequality constraints.
Hineq = extraParams{1};
fineq = extraParams{2};
rhsineq = extraParams{3};
Hineqmvec = Hineq*inputVariables(:);
cineq = 0.5*dot(inputVariables(:), Hineqmvec) + dot(fineq, inputVariables(:)) + rhsineq;


%% Compute equality constraints.
ceq = [];

if nargout > 2
    %% Compute constraint gradients.
    % To call the gradient code, notify the solver by setting the
    % SpecifyConstraintGradient option to true.
    cineqGrad = Hineqmvec + fineq;
    ceqGrad = [];
end
