function [obj, grad] = generatedObjective(inputVariables, extraParams)
%generatedObjective Compute objective function value and gradient
%
%   OBJ = generatedObjective(INPUTVARIABLES, EXTRAPARAMS) computes the
%   objective value OBJ at the point INPUTVARIABLES, using the extra
%   parameters in EXTRAPARAMS.
%
%   [OBJ, GRAD] = generatedObjective(INPUTVARIABLES, EXTRAPARAMS)
%   additionally computes the objective gradient value GRAD at the current
%   point.
%
%   Auto-generated by prob2struct on 12-Apr-2023 10:48:49

%% Map solver-based variables to problem-based.
x = inputVariables(:);

%% Compute objective function.
arg2 = (x(1) - 1000000);
arg4 = (x(2) - extraParams{1});
arg7 = x(1);
arg8 = x(2);
arg9 = ((arg7 .* arg8) - 2);
obj = ((arg2.^2 + arg4.^2) + arg9.^2);

if nargout > 1
    %% Compute objective gradient.
    % To call the gradient code, notify the solver by setting the
    % SpecifyObjectiveGradient option to true.
    arg10 = 1;
    arg11 = ((arg10.*2.*(arg9(:))).*arg7(:));
    arg12 = zeros([2,size(arg11,2)]);
    arg12(2,:) = arg11;
    arg13 = ((arg10.*2.*(arg9(:))).*arg8(:));
    arg14 = zeros([2,size(arg13,2)]);
    arg14(1,:) = arg13;
    arg15 = arg10;
    arg16 = (arg15.*2.*(arg4(:)));
    arg17 = zeros([2,size(arg16,2)]);
    arg17(2,:) = arg16;
    arg18 = (arg15.*2.*(arg2(:)));
    arg19 = zeros([2,size(arg18,2)]);
    arg19(1,:) = arg18;
    grad = arg12 + arg14 + arg17 + arg19;
    
end
end